#!/bin/bash

# curl -fsSLO https://bitbucket.org/softvisio/pgsql/raw/master/contrib/pgsql && chmod +x pgsql
# PGSQL_POSTGRES_PASSWORD=1 ./pgsql

set -e

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

export TAG=latest
export NAME=pgsql
export DOCKER_NAMESPACE=softvisio
export SERVICE=1
export CONTAINER_NAME=

# docker container restart policy, https://docs.docker.com/config/containers/start-containers-automatically/
export RESTART=unless-stopped

# seconds to wait for stop before killing container, https://docs.docker.com/engine/reference/commandline/stop/#options
export KILL_TIMEOUT=600

if [[ ! -z $PGSQL_POSTGRES_PASSWORD ]]; then
    PASSWORD="-e PGSQL_POSTGRES_PASSWORD=$PGSQL_POSTGRES_PASSWORD"
else
    echo "to see generated postgres password run: docker logs pgsql 2>&1 | grep \"GENERATED POSTGRES PASSWORD\""
fi

export DOCKER_CONTAINER_ARGS="
    $PASSWORD \
    -v pgsql:/var/local/dist/data \
    -v /var/run/postgresql:/var/run/postgresql \
    -p 5432:5432/tcp \
    --init \
    --shm-size=1g \
"

(source <(curl -fsSL https://bitbucket.org/softvisio/scripts/raw/master/docker.sh) "$@")
