# NOTE: deploy
# docker node update --label-add postgresql=primary `docker node inspect self --format "{{ .ID }}"`
# docker node update --label-add postgresql=sync `docker node inspect self --format "{{ .ID }}"`
# docker node update --label-add postgresql=async `docker node inspect self --format "{{ .ID }}"`

services:
  postgresql:
    image: ghcr.io/zerocluster/postgresql/18
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == primary"

    command: run --service=primary

    secrets:
      - { source: postgresql_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

    build:
      args:
        POSTGRESQL_VERSION: 18
        POSTGIS_VERSION: 3

  postgresql-sync:
    image: ghcr.io/zerocluster/postgresql/18
    depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 0 # must be equal to the replication.sync.numberOfStandbys in app config
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == sync"

    command: run --service=standby-sync

    secrets:
      - { source: postgresql_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

  postgresql-async:
    image: ghcr.io/zerocluster/postgresql/18
    depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == async"

    command: run --service=standby-async

    secrets:
      - { source: postgresql_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

secrets:
  postgresql_env.yaml: { file: env.yaml }

networks:
  network: ~

volumes:
  postgresql: ~
